apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: "mitre-tactic-command-control-webprotocol"
spec:
  endpointSelector:
    matchLabels:
      app: myService     // app label limits all endpoints which carry the labels app=myService
  ingress:
  - toPorts:
    - ports:
      - port: '80'      
        protocol: TCP     // the communication will be done by using TCP on port 80 // only APIs endpoints allowed will be GET and PUT with header K
      rules:                 
        http:
        - method: GET
          path: "/path1$"    
        - method: PUT
          path: "/path2$"    
          headers:
          - 'K-My-Header: true'
      
  action:
      Block  
  severity: 3         