apiVersion: v1
kind: KnoxNetworkPolicy
metadata:
  name: "mitre-tactic-command-control-webprotocol"
  namespace: multiubuntu
spec:
    matchLabels:
     severity: 5
     message: "block files following a pattern"
     selector:
       matchLabels:
         container: ubuntu-5
    ingress:        
    - toPorts:
      - ports:
        - port: '80'      
          protocol: TCP     // the communication will be done by using TCP on port 80 // only APIs endpoints allowed will be GET and PUT with header K
        rules:                 
        http:
        - method: GET
          path: "/path1$"    
        - method: PUT
          path: "/path2$"    
          headers:
          - 'K-My-Header: true'
      
    action:
      Block  
    severity: 3         
