apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "mitre-tactic-command-control-NSPorts"
spec:
  endpointSelector:
    matchLabels:
      role: backend     //enables all endpoints with different labels will  communicate only on port 80
  ingress:
  - fromEndpoints:
    - matchLabels:
        role: frontend
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
       
