apiVersion: v1
kind: KnoxNetworkPolicy
metadata:
  name: dns
  namespace: multiubuntu
spec:
  severity: 5
  message: "dns whitelist"
  selector:
    matchLabels:
      container: ubuntu-5
  egress:
  - toFQDNs:
    - matchPattern: "*.twitter.com" 
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP 
  
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"    
