apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-scheduled-task-job
spec:
  selectorLabels:
      nodeSelector:
          hostname: xyz
  process: 
        matchPaths: 
        - path: /var/spool/at
        - path: /var/spool/at/spool
        - path: /proc/loadavg
        - path: /var/run/utmp
        - path: /etc/at.allow
        - path: /etc/at.deny
  action:
    Audit
  severity: 2 
