apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-native-api
spec:
  selectorLabels:
      nodeSelector:
          hostname: xyz
  syscall:
    matchName:
    - name: syscall
    - parameter: *
    condition:
    - syscall.type: write
    - syscall.type: read
  action:
    BlockwithAudit
  severity: 5
