apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-execution
spec:
  selectorLabels:
      nodeSelector:
          hostname: xyz
  process: 
        matchPaths: 
        - path: /bin/pwd
        - path: /bin/bash
        - path: /bin/sh
        - path: /etc/init.d      #Some install scripts such as CHAOS make use of the file.
  action:
    BlockwithAudit
  severity: 4
